AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless URL Shortener

Globals:
  Function:
    Timeout: 10

  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,Authorization'"
      AllowOrigin: "'*'"

    Auth:
      DefaultAuthorizer: CognitoAuthorizer
      AddDefaultAuthorizerToCorsPreflight: false

      Authorizers:
        CognitoAuthorizer:
          UserPoolArn: "arn:aws:cognito-idp:ap-south-1:387512138365:userpool/ap-south-1_TeUUz43A6"

Resources:

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.14
      Architectures:
        - x86_64

      Environment:
        Variables:
          TABLE_NAME: UrlMappings

      Policies:
        - DynamoDBCrudPolicy:
            TableName: UrlMappings

      Events:
        ShortenApi:
          Type: Api
          Properties:
            Path: /shorten
            Method: post
            Auth:
              Authorizer: CognitoAuthorizer

  RedirectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: redirect/
      Handler: app.lambda_handler
      Runtime: python3.14

      Environment:
        Variables:
          TABLE_NAME: UrlMappings

      Policies:
        - DynamoDBCrudPolicy:
            TableName: UrlMappings

        - Statement:
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: arn:aws:sqs:ap-south-1:387512138365:ClickAnalyticsQueue

      Events:
        RedirectApi:
          Type: Api
          Properties:
            Path: /{shortCode}
            Method: get
            Auth:
              Authorizer: NONE

  AnalyticsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: analytics/
      Handler: app.lambda_handler
      Runtime: python3.14

      Environment:
        Variables:
          TABLE_NAME: UrlMappings

      Policies:
        - DynamoDBCrudPolicy:
            TableName: UrlMappings

        - S3CrudPolicy:
            BucketName: swasti-url-analytics-2026

      Events:
        ClickQueue:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:ap-south-1:387512138365:ClickAnalyticsQueue
            BatchSize: 1

Outputs:

  ShortenApi:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/shorten/"

  HelloWorldFunction:
    Description: Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn

  RedirectFunction:
    Description: Redirect Lambda Function ARN
    Value: !GetAtt RedirectFunction.Arn

  AnalyticsFunction:
    Description: Analytics Lambda Function ARN
    Value: !GetAtt AnalyticsFunction.Arn